#!/bin/dash
#written by Wanze Liu z5137189


legitdir='.legit'
sub_legitdir='.git'
fullpath="$legitdir/$sub_legitdir"
indexdir="objects"


# Subset 0
# function 1 inti
# initial the implicit folder ".legit/.git"

init() {
    if test -e  $legitdir
    then
        echo "legit-init: error: $legitdir already exists"
    else
        mkdir "$legitdir"
        mkdir "$legitdir/$sub_legitdir"
        if !( test -e "$fullpath/$indexdir" )
        then
            mkdir "$fullpath/$indexdir"
        fi
        #initial a HEAD file where it point to the current branch
        echo "master" > $fullpath/HEAD
        echo "Initialized empty legit repository in .legit"
    fi
}

init
