#!/bin/sh

legitdir='.legit'
sub_legitdir='.git'
fullpath="$legitdir/$sub_legitdir"
indexdir="objects"
# Subset 0
# Function 2 commit
# Saves a copy of all files in the index to the repository

add()
{
    if  test "$#" -eq 0
    then
        echo "Maybe you wanted to say 'git add .'?"
        exit 1
    fi
    if test -e  $legitdir
    then
        if !( test -e "$fullpath/$indexdir" )
        then
            mkdir "$fullpath/$indexdir"
        fi
        for file in $@
        do
            if !( test -e "$file" )
            then
                #if file exist in the object directory and not exist in the current directory,remove the file from objects directory
                if (test -e "$fullpath/$indexdir/$file")
                then
                    rm $fullpath/$indexdir/$file
                    exit 1
                fi

                echo "legit-add: error: can not open '$file'"
                if ( test -e "$fullpath/$indexdir/$file")
                then
                    rm "$fullpath/$indexdir/$file"
                fi
                continue
            elif ( (echo "$file" | egrep -v '[_a-zA-Z0-9\.\-]') || (echo "$file" | egrep -v '^[a-zA-Z0-9]') ) >/dev/null
            then
                echo "legit-add: error: invalid filename '$file'"
                continue
            else
                cp "$file" "$fullpath/$indexdir" >/dev/null 
            fi
        done
    else
        echo  "legit-add: error: no $legitdir directory containing legit repository exists"
        exit 1
    fi
}

commitseq()
{
    count=0
    while ( test $count -ge 0 )
    do
        if [ -d "$fullpath/.commit_$count" ]
        then
            count=$(( count+1 ))
        else
            return $count
        fi
    done
}


file_compare()
{   
    filename=".commit_$1"
    dir="$fullpath/$filename"
    #echo "$dir"
    #iterate the diractory to find differnt file 
    for f in `ls ${dir}`
        do  
            index_file="$fullpath/$indexdir/$f"
            if [ ! -f $index_file ]
            then
                return 1
            else
                diff "$index_file" "$dir/$f" >/dev/null
                if [ $? != 0 ]
                then
                    return 1
                else
                   # echo "same"
                    continue
                fi 
            fi 
        done
    #reverse iterate to find different file
    for ff in `ls "$fullpath/$indexdir/"`
    do
       # echo "$ff"
        obiect_dir="$dir/$ff"
        if [ ! -f $obiect_dir ]
        then
            #echo "$ff not exist in $dir"
            return 1
        else
            diff "$dir/$ff" "$obiect_dir" >/dev/null  
            if [ $? != 0 ]
            then
             #   echo 'differnet--------'
                return 1
            else
              #  echo "same+++++++++"
              continue
            fi
        fi    
    done 
}


commit()
{
    if [ ! -d $fullpath ]
    then 
        echo "legit-commit: error: no .legit directory containing legit repository exists"
        exit 1
    fi

    #[-a] option : update all the file from current directory to the object directory
    buff=0
   if ((test $# -ge 3) && (echo "$1" | egrep "\-a") && (echo "$2" | egrep "\-m")) >/dev/null 
       then
           for i in `ls $fullpath/$indexdir`
               do 
                   add $i
               done
            buff=1 
   fi

   if ( ( test $# -ge 2 ) && ( echo "$1" | egrep "\-m" ) ||  ( buff=1)) >/dev/null
    then
        #echo "-mmmmmmmmmmmmmmmmmmmmmmmmm"
        commitseq 
        last_num="$?" 
        commitdir="$fullpath/.commit_$last_num"
        #if  [ ! -d $fullpath/.commit_0 ]
        #then
        #    echo "asdasd"
        #fi
        #if ([ "`ls $fullpath/$indexdir`" != "" ])
        #then
         #   echo "&&&&&&&&&&&&&"
        #fi
        currentbranch=`cat $fullpath/HEAD`

        if ( [ ! -d $fullpath/.commit_0 ] && [ "`ls $fullpath/$indexdir`" != "" ]) 
        then
            mkdir $fullpath/.commit_0
            echo "$@" | sed "s/-m //" > "$fullpath/.commit_$last_num/.commit_message"
            cp $fullpath/$indexdir/* $commitdir >/dev/null  2>&1
            echo "COMMIT:$last_num" >> $fullpath/Branch.master
            echo "Committed as commit $last_num"
            exit 0
        fi

        pre_seq=$((last_num-1))
        file_compare $pre_seq
        flag=$?
       # echo "singal is $flag"
        #echo $last_num
        if ( test  $flag -eq 1 )
        then
            mkdir $commitdir
            echo "$@" | sed "s/-m //" > "$fullpath/.commit_$last_num/.commit_message"
            cp $fullpath/$indexdir/* $commitdir >/dev/null  2>&1
            echo "COMMIT:$last_num" >> $fullpath/Branch.$currentbranch
            echo "Committed as commit $last_num"
        else
            echo "nothing to commit"
        fi
    else
        echo "usage: legit-commit [-a] -m commit-message"
        exit 1
    fi
}

commit $@


