#!/bin/dash
legitdir='.legit'
sub_legitdir='.git'
fullpath="$legitdir/$sub_legitdir"
indexdir="objects"

# Subset 0
# function 4 log
# print all the log in the .commit_message with its number

log()
{
    if [ ! -d $fullpath ]
    then
        echo "legit-log: error: no .legit directory containing legit repository exists"
        exit 1

    elif [ ! -d $fullpath/$indexdir ]
    then
        echo 'legit-log: error: your repository does not have any commits yet'
        exit 1
    fi

    flag=0
    for file in $1/.commit*
    do
        flag=1
    done
    if ( test  $flag -eq 0 )
    then 
        echo 'legit-log: error: your repository does not have any commits yet'
        exit 1
    fi

    for file in $1/.commit*
    do
        num=`echo $file | sed "s/.*_//"`
        message=`cat $file/.commit_message`
        array[$num]=$message
        #echo ${array[*]}
        #echo "$num $message"
    done
    len=${#array[*]}
#    for ((i=$len-1;i>=0;i--))
#    do
#        echo  "$i ${array[$i]}"
#    done
    count=$len
    let count-=1
    while ( test $count -ge 0 )
    do 
        echo "$count ${array[$count]}"
        let count-=1
    done
}

log $fullpath



