#!/bin/sh
# written by Wanze Liu

legitdir='.legit'
sub_legitdir='.git'
fullpath="$legitdir/$sub_legitdir"
indexdir="objects"

# Subset 0
# function 4 log
# The legit­show should print the contents of the specified file as of the specified commit. If the commit is omitted the contents of the file in the index should be printed.
commitseq()
{
    count=0
    while ( test $count -ge 0 )
    do
        if [ -d "$fullpath/.commit_$count" ]
        then
            count=$(( count+1 ))
        else
            return $count
        fi
    done
}

show()
{
    if [ ! -d $fullpath ]
    then
        echo "legit-show: error: no .legit directory containing legit repository exists"
        exit 1

    elif [ ! -d $fullpath/$indexdir ]
    then
        echo 'legit-show: error: your repository does not have any commits yet'
        exit 1
    fi
    if !( test $# -eq 1 )
    then 
        echo "usage: legit-show <commit>:<filename>"
        exit 1
    elif ( echo "$1" | grep -v ":" ) > /dev/null
    then
        echo "legit-show: error: invalid object $1"
        exit 1
    fi
    # get the version number and filename
    filename=`echo $1 | sed "s/.*://"`
    num=`echo $1 | sed "s/:.*//"`
    #aviod invalid input
   # if !( echo "$num" | egrep "^[0-9]+$")>/dev/null
   # then
   #     echo "legit-show: error: unknown commit '$num'"
   #     exit 1
   # fi
   if !([ "$num" == "" ])
   then 
    
        if [ ! -d $fullpath/.commit_$num ]
        then
             echo "legit-show: error: unknown commit '$num'"
             exit 1
        fi
        if [ ! -f $fullpath/.commit_$num/$filename ]
        then
            echo "legit-show: error: '$filename' not found in commit $num"
            exit 1
        fi
        cat $fullpath/.commit_$num/$filename
    else
        commitseq 
        last_num="$?"
        pre_seq=$((last_num-1))
        if [ ! -f $fullpath/.commit_$pre_seq/$filename ]
        then
            echo "legit-show: error: '$filename' not found in commit $num"
            exit 1
        fi 
        cat $fullpath/.commit_$pre_seq/$filename 
   fi 

}

show $@
