#!/bin/dash
#written by Wanze Liu , z5137189

legitdir='.legit'
sub_legitdir='.git'
fullpath="$legitdir/$sub_legitdir"
indexdir="objects"

# Subset 0
# function 2 add
# adds the contents of one or more files to the "index"

add()
{
    if  test "$#" -eq 0
    then
        echo "Maybe you wanted to say 'git add .'?"
        exit 1
    fi
    if test -e  $legitdir
    then
        if !( test -e "$fullpath/$indexdir" )
        then
            mkdir "$fullpath/$indexdir"
        fi
        # traverse the file that need to add 
        for file in $@
        do  
            #if file not exist in the current directory
            if !( test -e "$file" )
            then
                #if file exist in the object directory and not exist in the current directory,remove the file from objects directory
                if (test -e "$fullpath/$indexdir/$file")
                then
                    rm $fullpath/$indexdir/$file
                    exit 1
                fi

                echo "legit-add: error: can not open '$file'"
                if ( test -e "$fullpath/$indexdir/$file")
                then 
                    rm "$fullpath/$indexdir/$file"
                fi
                continue
            elif ( (echo "$file" | egrep -v '[_a-zA-Z0-9\.\-]') || (echo "$file" | egrep -v '^[a-zA-Z0-9]') ) >/dev/null
            then
                echo "legit-add: error: invalid filename '$file'"
                continue
            else 
                cp "$file" "$fullpath/$indexdir"
            fi
        done
    else
        echo  "legit-add: error: no $legitdir directory containing legit repository exists"
        exit 1
    fi
}

add $@ 





