#!/bin/sh
legitdir='.legit'
sub_legitdir='.git'
fullpath="$legitdir/$sub_legitdir"
indexdir="objects"

# Subset 0
# function 4 log
# print all the log in the .commit_message with its number

log()
{
    for file in $1/.commit*
    do
        num=`echo $file | sed "s/.*_//"`
        message=`cat $file/.commit_message`
        array[$num]=$message
        #echo ${array[*]}
        #echo "$num $message"
    done
    len=${#array[*]}
    echo $len
    for ((i=$len-1;i>=0;i--))
    do
        echo  "$i ${array[$i]}"
    done 
}

log $fullpath



