#!/bin/dash
#written by Wanze Liu z5137189



legitdir='.legit'
sub_legitdir='.git'
fullpath="$legitdir/$sub_legitdir"
indexdir="objects"

# Subset 0
# function 4 log
# print all the log in the .commit_message with its number

log()
{   

    if [ ! -d $fullpath ]
    then
        echo "legit-log: error: no .legit directory containing legit repository exists"
        exit 1
    elif [ ! -d $fullpath/$indexdir ]
    then
        echo 'legit-log: error: your repository does not have any commits yet'
        exit 1
    fi
    count=`ls $fullpath/$indexdir |wc -w`
    if  ( test $count -eq 0 )
    then
        echo 'legit-log: error: your repository does not have any commits yet'
        exit 1
    fi

    flag=0
    for file in $1/.commit*
    do
        flag=1
    done
    if ( test  $flag -eq 0 )
    then 
        echo 'legit-log: error: your repository does not have any commits yet'
        exit 1
    fi
    #iterate all the commit file to get commit message store in the .commit_message and print it out
    for file in `ls -ra $1 | grep ".comm"`
    do
        num=`echo $file | sed "s/.*_//"`
        message=`cat $fullpath/$file/.commit_message`
        echo "$num $message"
    done
}

log $fullpath



