#!/bin/bash

legitdir='.legit'
sub_legitdir='.git'
fullpath="$legitdir/$sub_legitdir"
indexdir="objects"
flag=0
# Subset 0
# Function 2 commit
# Saves a copy of all files in the index to the repository

commitseq()
{
    count=0
    while ( test $count -ge 0 )
    do
        if [ -d "$fullpath/.commit_$count" ]
        then
            count=$(( count+1 ))
        else
            return $count
        fi
    done
}


file_compare()
{   
    filename=".commit_$1"
    dir="$fullpath/$filename"
    echo "$dir"
    #iterate the diractory to find differnt file 
    for f in `ls ${dir}`
        do  
            index_file="$fullpath/$indexdir/$f"
            if [ ! -f $index_file ]
            then
                return 1
            else
                diff "$index_file" "$dir/$f" >/dev/null
                if [ $? != 0 ]
                then
                #    echo "$index_file"
                #    echo "$dir/$f"
                 #   echo `diff $dir/$f $index_file`
                    echo "different *******"
                    return 1
                else
                    echo "same"
                fi 
            fi 
        done
    #reverse iterate to find different file
    for ff in `ls "$fullpath/$indexdir/"`
    do
        echo "$ff"
        obiect_dir="$dir/$ff"
        if [ ! -f $obiect_dir ]
        then
            echo "not exist in $dir"
            return 1
        else
            diff "$dir/$ff" "$obiect_dir" 
            if [ $? != 0 ]
            then
                echo 'differnet ___--------'
                return 1
            else
                echo "same+++++++++"
            fi
        fi    
    done

}


commit()
{
    if [ ! -d $fullpath ]
    then 
        echo "legit-commit: error: no .legit directory containing legit repository exists"
        exit 1
    fi
    if ([[ "$1" =~ '-m' && $2 ]])
    then
        commitseq 
        last_num="$?" 
        commitdir="$fullpath/.commit_$last_num"
        mkdir $commitdir 
        echo "$2" > "$fullpath/.commit_$last_num/.commit_message"
        pre_seq=$((last_num-1))
        file_compare $pre_seq 
        echo "singal is $?"
        if (test  $? -eq 0  )
        then 
            cp $fullpath/$indexdir/* $commitdir 
            echo "Committed as commit $last_num"
        else
            echo "nothing to commit"
        fi
    else
        echo "usage: legit-commit [-a] -m commit-message"
        exit 1
    fi
}

commit $@


