#!/usr/bin/perl -w


$legitdir='.legit';
$sub_legitdir='.git';
$fullpath="$legitdir/$sub_legitdir";
# $indexdir="objects";


sub instruction{
	print "Usage: legit.pl <command> [<args>]\n";
    print "These are the legit commands:\n";
    print "   init       Create an empty legit repository\n";
    print "   add        Add file contents to the index\n";
    print "   commit     Record changes to the repository\n";
    print "   log        Show commit log\n";
    print "   show       Show file at particular state\n";
    print "   rm         Remove files from the current directory and from the index\n";
    print "   status     Show the status of files in the current directory, index, and repository\n";
    print "   branch     list, create or delete a branch\n";
    print "   checkout   Switch branches or restore current directory files\n";
    print "   merge      Join two development histories together\n\n";
    exit 1;
}

sub is_exist{
	if ( ! -d "$legitdir" ){
		print "legit-branch: error: no $legitdir directory containing legit repository exists\n";
		exit 1;
	}
	if ( -d "$legitdir" && &commitseq == -1){
		print "legit-branch: error: your repository does not have any commits yet\n";
		exit 1;
	}
}

# if (@ARGV=0){
# 	&instruction();
# }
sub commitseq{
	$count=0;
	if ( ! -d "$fullpath/.commit_0"){
		return -1;
	}
	while ( -d "$fullpath/.commit_$count" ){
		$count+=1;
	}
	return $count;
}



sub check_legit {
	&is_exist;
	$seq= &commitseq;
	print "$seq\n";
}



&check_legit